### ISSUE TITLE
Cannot import simplecrypt?

### ISSUE THREAD

**Issue by scheung38** [eriktaubeneck/flask-chat#1]
Hi Erik

![screen shot 2015-08-18 at 00 48 46](https://cloud.githubusercontent.com/assets/1273014/9319180/742ab852-4543-11e5-98c9-1181ccf6785f.png)

I cannot resolve Flask in factory.py, line 2:
from ordbok.flask_helper import Flask (Why import Flask this way?)

ordbok.config_private.py, line 4:
import simplecrypt
ImportError: No module named simplecrypt

doc says:
gunicorn -k flask_sockets.worker server:app -b 127.0.0.1:4999 --debug

But actual ProcFile:
web: gunicorn -k flask_sockets.worker server:app

In config.yml which REDIS_URL setting to use:

'''
DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SITE_URL: 'localhost:4999'
  REDIS_URL: 'ordbok_local_config'    //or this?
# REDIS_URL: 'redis://localhost'

'''

Seb

**Comment by eriktaubeneck** [comment]
have you tried to install simple crypt with `pip install simplecrypt`?

**Comment by eriktaubeneck** [comment]
also the latest version of ordbok has a more graceful way of working with flask: http://ordbok.readthedocs.org/en/latest/get-started/

I haven't updated this repo since that update.

**Comment by scheung38** [comment]
within my virtualenv

(pyenv2.7.9)$pip install simplecrypt
Collecting simplecrypt
  Could not find a version that satisfies the requirement simplecrypt (from versions: )
No matching distribution found for simplecrypt

Though in Pycharm I can see simplecrypto 0.3.3, maybe not the same?

Also cannot resolve LocalProxy in extensions.py:
from werkzeug import LocalProxy

But later tried pip install simple-crypt? (With hypen?)
Then changed factory.py but still complains 

```
import redis
from flask import Flask
from ordbok.flask_helper import FlaskOrdbok

from app import sockets, chat
from app.views.index import index_bp
from app.views.chat import register_chat_routes

def create_app(config=None, environment=None):
    app = Flask(__name__)
    ordbok = FlaskOrdbok(app)
    ordbok.load()

    app.config['ENVIRONMENT'] = environment
    app.config.load(ordbok)
    app.config.update(config or {})
    if not (app.config['ENVIRONMENT'] == 'development' or
            app.config['TESTING']):
        app.config['SERVER_NAME'] = app.config['SITE_URL']

    sockets.init_app(app)
    app.redis = redis.from_url(app.config['REDIS_URL'])

    chat.init_app(app)
    chat.start()
    app.register_blueprint(index_bp)
    register_chat_routes(app, sockets)

    return app
```

```
/Users/minminsanjose/anaconda/envs/pyenv2.7.9/bin/python /Users/minminsanjose/PycharmProjects/flask-chat/manage.py
Traceback (most recent call last):
  File "/Users/minminsanjose/PycharmProjects/flask-chat/manage.py", line 4, in <module>
    app = create_app()
  File "/Users/minminsanjose/PycharmProjects/flask-chat/app/factory.py", line 14, in create_app
    ordbok.load()
  File "/Users/minminsanjose/anaconda/envs/pyenv2.7.9/lib/python2.7/site-packages/ordbok/ordbok.py", line 56, in load
    config_file.load(config_files_lookup)
  File "/Users/minminsanjose/anaconda/envs/pyenv2.7.9/lib/python2.7/site-packages/ordbok/config_file.py", line 28, in load
    self._check_required_keys()
  File "/Users/minminsanjose/anaconda/envs/pyenv2.7.9/lib/python2.7/site-packages/ordbok/config_file.py", line 119, in _check_required_keys
    raise OrdbokMissingKeyException(key, self)
ordbok.exceptions.OrdbokMissingKeyException
```

Could you update as I have not seen it working since git cloning project into Pycharm thanks

**Comment by eriktaubeneck** [comment]
This is just an example application, not a fully fleshed out application. It looks like you likely need to set the `REDIS_URL` as described in the readme. It may also be helpful to look at the [Ordbok docs](http://ordbok.readthedocs.org/en/latest/) to understand how the config is working.

**Comment by agmezr** [comment]
For me it worked with `pip install simple-crypt` , note the `-` in the name
